---
- name: Install ntp
  apt: name=ntp state=present update_cache=true

- name: ntp configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf owner=0 mode=0644

- name: run ntp
  service: name=ntp state=running enabled=true
